#!/usr/bin/env node
// Runs a compiled headless Effect.Test program (see PerfRunner.elm generated by run.py)
// and prints a single JSON line with the test output and timing/memory stats.
//
// Usage: node run-tests.js <compiled-elm.js> <app-root-dir>
//
// Effect.Test.viewerWith file loads (addStringFile/addBytesFile) issue XMLHttpRequests
// with URLs like "/tests/data/foo.json". Node has no XMLHttpRequest, so a minimal shim
// is installed that serves those paths from <app-root-dir> synchronously from disk.

const fs = require("fs");
const path = require("path");

const compiledPath = path.resolve(process.argv[2]);
const appRoot = path.resolve(process.argv[3]);

class FileXMLHttpRequest {
    constructor() {
        this.listeners = {};
        this.responseType = "";
        this.status = 0;
        this.statusText = "";
        this.response = null;
        this.responseURL = "";
        this.timeout = 0;
    }

    addEventListener(type, fn) {
        (this.listeners[type] = this.listeners[type] || []).push(fn);
    }

    setRequestHeader() {}

    getAllResponseHeaders() {
        return "";
    }

    open(method, url) {
        this.url = url;
    }

    abort() {}

    send() {
        setImmediate(() => {
            const urlPath = decodeURIComponent(this.url.split("?")[0]);
            const filePath = path.join(appRoot, urlPath);
            this.responseURL = this.url;
            try {
                const buffer = fs.readFileSync(filePath);
                this.status = 200;
                this.statusText = "OK";
                this.response =
                    this.responseType === "arraybuffer"
                        ? buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength)
                        : buffer.toString("utf8");
            } catch (err) {
                this.status = 404;
                this.statusText = "Not Found";
                this.response = this.responseType === "arraybuffer" ? new ArrayBuffer(0) : "";
                console.error("file not found for XHR: " + filePath);
            }
            for (const fn of this.listeners["load"] || []) {
                fn.call(this);
            }
        });
    }
}

global.XMLHttpRequest = FileXMLHttpRequest;

const { Elm } = require(compiledPath);
const moduleName = Object.keys(Elm)[0];

const timeoutMs = 30 * 60 * 1000;
const killTimer = setTimeout(() => {
    console.log(JSON.stringify({ ok: false, error: "timed out after " + timeoutMs + "ms" }));
    process.exit(2);
}, timeoutMs);

const t0 = process.hrtime.bigint();
const app = Elm[moduleName].init();
app.ports.output.subscribe((value) => {
    const elapsedMs = Number(process.hrtime.bigint() - t0) / 1e6;
    clearTimeout(killTimer);
    const usage = process.resourceUsage();
    const mem = process.memoryUsage();
    console.log(
        JSON.stringify({
            ok: true,
            // null means every test passed; otherwise it's the failure report string
            output: value,
            elapsed_ms: Math.round(elapsedMs),
            max_rss_mb: Math.round(usage.maxRSS / 1024),
            heap_used_mb: Math.round(mem.heapUsed / 1048576),
        })
    );
    process.exit(0);
});
